# Generated by Django 6.0.4 on 2026-04-28 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_father', to='api.livestock')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_mother', to='api.livestock')),
            ],
            options={
                'db_table': 'Ganado',
            },
        ),
    ]
