# Generated by Django 6.0.4 on 2026-04-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(db_column='ID_batch', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('description', models.CharField(db_column='Description', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.AutoField(db_column='ID_feeding', primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, db_column='Date')),
                ('food_type', models.CharField(db_column='Food_Type', max_length=50)),
                ('quantity_kg', models.DecimalField(db_column='Quantity_kg', decimal_places=2, max_digits=10)),
                ('schedule', models.CharField(db_column='Schedule', max_length=20)),
                ('observations', models.TextField(db_column='Observations', null=True)),
            ],
            options={
                'db_table': 'Feeding_Log',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='livestock',
            options={'managed': False},
        ),
    ]
