# Generated by Django 5.0.4 on 2026-05-19 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_batch_feedinglog_alter_livestock_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(db_column='ID_cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthAction',
            fields=[
                ('id', models.AutoField(db_column='ID_accion', primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(db_column='Tipo_evento', max_length=100)),
                ('dosis', models.CharField(db_column='Dosis', max_length=50)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
            ],
            options={
                'db_table': 'Acciones_sanitarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.AutoField(db_column='ID_movimiento', primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(db_column='Tipo_movimiento', max_length=20)),
                ('cantidad', models.DecimalField(db_column='Cantidad', decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(blank=True, db_column='Costo_Unitario', decimal_places=2, max_digits=10, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, db_column='Fecha_movimiento')),
                ('motivo', models.CharField(db_column='Motivo', max_length=100)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Movimientos_Inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.AutoField(db_column='ID_ordeño', primary_key=True, serialize=False)),
                ('liters_produced', models.DecimalField(db_column='Litros_producidos', decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
            ],
            options={
                'db_table': 'Produccion_leche',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(db_column='ID_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('unidad_medida', models.CharField(db_column='Unidad_medida', max_length=50)),
                ('precio_actual', models.DecimalField(db_column='Precio_actual', decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(db_column='Stock', decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(db_column='Categoria', default='Venta', max_length=50)),
            ],
            options={
                'db_table': 'Productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(db_column='ID_venta', primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True, db_column='Fecha_venta')),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=12)),
                ('status', models.CharField(db_column='Estado', default='Completada', max_length=50)),
            ],
            options={
                'db_table': 'Ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.AutoField(db_column='ID_detalle', primary_key=True, serialize=False)),
                ('tipo_item', models.CharField(db_column='Tipo_item', max_length=50)),
                ('cantidad', models.DecimalField(db_column='Cantidad', decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=12)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(db_column='ID_salida', primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField(auto_now_add=True, db_column='Fecha_salida')),
                ('motivo_salida', models.CharField(db_column='Motivo_salida', max_length=50)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Salidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeightControl',
            fields=[
                ('id', models.AutoField(db_column='ID_pesaje', primary_key=True, serialize=False)),
                ('peso', models.DecimalField(db_column='Peso', decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'db_table': 'Control_pesaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Gerente', 'Gerente'), ('Capataz', 'Capataz')], default='Capataz', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Profiles',
            },
        ),
    ]
