# Generated by Django 5.0.4 on 2026-06-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cashregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
