# Generated by Django 5.0.4 on 2026-06-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cashregister_estado_marketprice_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='marketprice',
            name='estado',
        ),
    ]
