# Generated by Django 5.0.4 on 2026-06-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_cashregister_estado_remove_marketprice_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feedinglog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='healthaction',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='milkproduction',
            options={'managed': True, 'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='salesdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='salida',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='weightcontrol',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='cashregister',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
