# Generated by Django 5.0.4 on 2026-06-05 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_batch_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedinglog',
            name='food_type',
        ),
        migrations.AddField(
            model_name='batch',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='batch',
            field=models.ForeignKey(blank=True, db_column='ID_batch', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.batch'),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='producto',
            field=models.ForeignKey(db_column='ID_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.products'),
        ),
        migrations.AddField(
            model_name='healthaction',
            name='animal',
            field=models.ForeignKey(blank=True, db_column='ID_animal', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.livestock'),
        ),
        migrations.AddField(
            model_name='healthaction',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='ID_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.products'),
        ),
        migrations.AddField(
            model_name='milkproduction',
            name='animal',
            field=models.ForeignKey(blank=True, db_column='ID_ganado', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.livestock'),
        ),
        migrations.AddField(
            model_name='milkproduction',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(blank=True, db_column='ID_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.client'),
        ),
        migrations.AddField(
            model_name='sales',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='ganado',
            field=models.ForeignKey(blank=True, db_column='ID_ganado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.livestock'),
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='ID_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.products'),
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='venta',
            field=models.ForeignKey(blank=True, db_column='ID_venta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.sales'),
        ),
        migrations.AddField(
            model_name='salida',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salida',
            name='ganado',
            field=models.ForeignKey(blank=True, db_column='ID_ganado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.livestock'),
        ),
        migrations.AddField(
            model_name='salida',
            name='venta',
            field=models.ForeignKey(blank=True, db_column='ID_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sales'),
        ),
        migrations.AddField(
            model_name='weightcontrol',
            name='animal',
            field=models.ForeignKey(blank=True, db_column='ID_ganado', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.livestock'),
        ),
        migrations.AddField(
            model_name='weightcontrol',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
