# Generated by Django 5.0.4 on 2026-06-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_feedinglog_food_type_batch_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.AutoField(db_column='ID_alerta', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=50)),
                ('texto', models.CharField(db_column='Texto', max_length=255)),
                ('leida', models.BooleanField(db_column='Leida', default=False)),
                ('identificador_unico', models.CharField(db_column='Identificador', max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion')),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Alertas_Sistema',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
