# Generated by Django 5.0.4 on 2026-06-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_systemalert_alter_healthaction_animal'),
    ]

    operations = [
       
    ]
