# Generated by Django 5.0.4 on 2026-06-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_healthaction_animal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestock',
            options={'managed': True},
        ),
    ]
