# Generated by Django 5.0.4 on 2026-06-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_livestock_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='father',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='weight',
        ),
        migrations.AddField(
            model_name='livestock',
            name='batch',
            field=models.ForeignKey(blank=True, db_column='batch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.batch'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.marketprice'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='edad',
            field=models.IntegerField(blank=True, db_column='Edad', null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='estado',
            field=models.IntegerField(db_column='Estado', default=1),
        ),
        migrations.AddField(
            model_name='livestock',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, db_column='Fecha_nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='id_madre',
            field=models.ForeignKey(blank=True, db_column='ID_madre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_madre', to='api.livestock'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='id_padre',
            field=models.ForeignKey(blank=True, db_column='ID_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_padre', to='api.livestock'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Ganados/'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='metodo_obtencion',
            field=models.CharField(blank=True, db_column='Metodo_obtencion', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='nombre',
            field=models.CharField(blank=True, db_column='Nombre', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='peso',
            field=models.DecimalField(blank=True, db_column='Peso', decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='qr_code',
            field=models.ImageField(blank=True, db_column='Codigo_QR', null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='raza',
            field=models.CharField(blank=True, db_column='Raza', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='sexo',
            field=models.CharField(blank=True, db_column='Sexo', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='valor_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='healthaction',
            name='animal',
            field=models.ForeignKey(blank=True, db_column='ID_ganado', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.livestock'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='id',
            field=models.AutoField(db_column='ID_ganado', primary_key=True, serialize=False),
        ),
    ]
