# Generated by Django 5.0.4 on 2026-06-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_livestock_birth_date_remove_livestock_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='chapa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='costo_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
