# Generated by Django 5.0.4 on 2026-06-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_livestock_chapa_livestock_costo_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='chapa',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
