# Generated by Django 5.0.4 on 2026-06-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_livestock_chapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='estado',
            field=models.IntegerField(db_column='Activo', default=1),
        ),
    ]
