# Generated by Django 5.0.4 on 2026-06-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_sales_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdetails',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='sales',
            name='status',
        ),
        migrations.AlterField(
            model_name='sales',
            name='estado',
            field=models.IntegerField(db_column='Estado', default=1),
        ),
    ]
